#debug: true

build:
  image: firecyberice/rpi-docker:1.10.0-dev
  extra_hosts:
    - docker
  environment:
    - DOCKER_HOST=tcp://localhost:2375
    - PACKAGECLOUD_API_TOKEN=$$PACKAGECLOUD_API_TOKEN
    - PACKAGECLOUD_USER_REPO=$$PACKAGECLOUD_USER_REPO
  commands:
    - apk update && apk add git curl bash tree
    - export VERSION=$(cat VERSION)
    - export BUILD_RESULTS=/drone/src/buildresult
    - export TIMESTAMP=$(date +"%Y-%m-%d_%H%M")
    - export REPO=$(git rev-parse --short HEAD)
    - export buildpath=$(pwd)
    - echo $buildpath
    - export PACKAGE_RELEASE_VERSION=${DRONE_BUILD_NUMBER:-1}
    - export PACKAGE_VERSION=${VERSION}-${PACKAGE_RELEASE_VERSION}
    - export PACKAGE_NAME=docker-compose
#_${PACKAGE_VERSION}
    - export folder=$BUILD_RESULTS/${VERSION}-${TIMESTAMP}
    - mkdir -p $folder/package
    - git clone -b $VERSION https://github.com/docker/compose
    - cp -r patches/* compose/
    - ./fix_pyinstaller.sh
    - cd compose
    - ./script/build/linux
    - echo "+++++ prepare dist +++++"
    - cp dist/docker-compose-* $folder/docker-compose-`uname -s`-`uname -m`
    - cd $folder
    - sha256sum docker-compose-`uname -s`-`uname -m` >docker-compose-`uname -s`-`uname -m`.sha256
    - echo "+++++ create deb +++++"
    - docker run -t -v $buildpath:$buildpath -v $folder:$folder -e PACKAGE_NAME -e PACKAGE_VERSION -e folder -e buildpath resin/rpi-raspbian:jessie bash -c "echo $PACKAGE_NAME%$PACKAGE_VERSION%$buildpath%$folder && cd $buildpath && ./build_debian_package.sh $PACKAGE_NAME $PACKAGE_VERSION $folder"
    - echo "+++++ upload deb to package cloud +++++"
      # see documentation for this api call at https://packagecloud.io/docs/api#resource_packages_method_create
      # distro_version_id=24 denotes debian wheezy
    - curl -X POST https://${PACKAGECLOUD_API_TOKEN}:@packagecloud.io/api/v1/repos/${PACKAGECLOUD_USER_REPO}/packages.json -F "package[distro_version_id]=24" -F "package[package_file]=@${folder}/package/${PACKAGE_NAME}.deb"
      # distro_version_id=25 denotes debian jessie
    - curl -X POST https://${PACKAGECLOUD_API_TOKEN}:@packagecloud.io/api/v1/repos/${PACKAGECLOUD_USER_REPO}/packages.json -F "package[distro_version_id]=25" -F "package[package_file]=@${folder}/package/${PACKAGE_NAME}.deb"
      # distro_version_id=153 denotes raspbian wheezy
    - curl -X POST https://${PACKAGECLOUD_API_TOKEN}:@packagecloud.io/api/v1/repos/${PACKAGECLOUD_USER_REPO}/packages.json -F "package[distro_version_id]=153" -F "package[package_file]=@${folder}/package/${PACKAGE_NAME}.deb"
      # distro_version_id=154 denotes raspbian jessie
    - curl -X POST https://${PACKAGECLOUD_API_TOKEN}:@packagecloud.io/api/v1/repos/${PACKAGECLOUD_USER_REPO}/packages.json -F "package[distro_version_id]=154" -F "package[package_file]=@${folder}/package/${PACKAGE_NAME}.deb"


compose:
  docker:
    privileged: true
    image: firecyberice/rpi-docker:1.10.0-dev-dind

publish:
  s3:
    acl: public-read
    region: $$AWS_DEFAULT_REGION
    bucket: $$AWS_BUCKET
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: /drone/src/buildresult
    target: arm-binaries/compose/
    recursive: true
#    when:
#      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true
